Improved version of the charter and the explainer
w3c/lds-wg-charter pull request #72
Opened 2021-05-08 15:23 UTC by iherman

Version after the discussion on the SWIG mailing list and related issues.

- the relationship between LD vs. RDF is detailed in the explainer
- additional non-normative note on additional proof approaches 
- removal of some too 'marketing' type statements
- addition of out-of-scope entries on issues related to LD when going beyond simple RDF datasets

2021-05-08 16:59 UTC, afs commented on index.html
> +                (For the usage of the terms “RDF” and “Linked Data", see the <a href="./explainer.html#ld-vs-rdf">terminological note</a> in the explainer document.)
```suggestion
                (For the usage of the terms “RDF” and “Linked Data", see the <a href="./explainer.html#ld-and-rdf">terminological note</a> in the explainer document.)                
```

2021-05-08 17:00 UTC, afs commented on index.html
> +                (For the usage of the terms “RDF” and “Linked Data", see the <a href="./explainer.html#ld-vs-rdf">terminological note</a> in the explainer document.)
```suggestion
                (For the usage of the terms “RDF” and “Linked Data", see the <a href="./explainer.html#ld-and-rdf">terminological note</a> in the explainer document.)                
```

2021-05-10 11:17 UTC, pchampin approved these changes

2021-05-10 11:39 UTC, philarcher requested changes
I've created a PR on this PR that tries to clarify that it's the underlying graph that we want to sign/prove, not the specific block of data. I think it's important to make this clarification

2021-05-10 13:51 UTC, merged